In [2]:
"""
Data Source: https://www.kaggle.com/datasets/datascikhan/e-commerce-sales-and-customer-analytics
"""

'\nData Source: https://www.kaggle.com/datasets/datascikhan/e-commerce-sales-and-customer-analytics\n'

In [3]:
import pandas as pd
from datetime import date

In [4]:
df = pd.read_csv('ecommerce_sales_customer_analytics_150k.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 47.6 MB

In [5]:
df.describe(include='all')

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
count,138116,138116,138116,138116,138116,138116,138116,138116.000000,138116,138116,...,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116,138116.000000
unique,138116,1826,68991,4,4,24911,21564,NaN,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
top,ORD-301242,2025-12-30,14:55:55,Completed,Mobile App,CUST-014687,John Smith,NaN,Female,Consumer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN
freq,1,143,11,113559,55318,19,97,NaN,66439,75636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137782,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.862681,NaN,NaN,...,237.621614,122.462933,22.278080,1282.503575,708.903449,551.322046,45.065997,8971.639047,NaN,6.990559
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.467676,NaN,NaN,...,378.779459,140.939368,16.022739,1169.274669,730.044970,516.300936,13.120357,4430.506588,NaN,2.444166
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,NaN,...,0.000000,0.340000,0.000000,5.800000,1.970000,-1281.590000,-59.550000,22.550000,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.000000,NaN,NaN,...,26.327500,34.650000,9.820000,448.200000,207.667500,190.757500,38.880000,5713.570000,NaN,5.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.000000,NaN,NaN,...,103.285000,77.010000,19.190000,950.760000,478.955000,408.395000,46.990000,8392.525000,NaN,7.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.000000,NaN,NaN,...,277.125000,156.200000,30.750000,1744.582500,953.762500,752.845000,53.770000,11651.030000,NaN,9.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,NaN,...,6759.020000,2091.520000,149.520000,16218.000000,9963.410000,7083.680000,77.590000,30268.440000,NaN,20.000000

# CLEANING

In [6]:
df.columns

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [7]:
# relevant data
df[['order_id', 'order_date', 'order_time', 'order_status',    
       'customer_segment', 'customer_type', 'customer_country', 'region',
       'payment_status', 'currency', 'shipping_method', 'delivery_days', 
       'estimated_delivery_days', 'delivery_status', 'return_status', 
       'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'quantity', 'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer','customer_order_count']]

,order_id,order_date,order_time,order_status,customer_segment,customer_type,customer_country,region,payment_status,currency,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Consumer,Loyal,USA,South,Paid,USD,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Premium,Loyal,Germany,South,Pending,EUR,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Premium,Loyal,USA,East,Paid,USD,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Consumer,Loyal,USA,South,Paid,USD,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Consumer,Loyal,India,West,Paid,INR,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Consumer,Loyal,USA,East,Paid,USD,...,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63,True,14
138112,ORD-487614,2023-07-22,09:13:25,Returned,Premium,Loyal,USA,West,Refunded,USD,...,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74,True,10
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Consumer,Loyal,UK,North,Failed,GBP,...,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68,True,15
138114,ORD-252033,2022-04-06,14:50:07,Completed,Consumer,Loyal,USA,Central,Paid,USD,...,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00,True,5
138115,ORD-528577,2022-11-23,11:46:00,Completed,Consumer,Loyal,USA,West,Paid,USD,...,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38,True,5

In [26]:
# to date datatype
df['order_date'] = pd.to_datetime(df['order_date'])

In [27]:
# unifying currency to USD
moneyCols = ['gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
    'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
    'customer_lifetime_value']
df[['currency'] + moneyCols]

,currency,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value
0,USD,1350.19,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68
1,EUR,3144.64,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48
2,USD,522.81,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44
3,USD,544.62,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30
4,INR,2474.52,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10
...,...,...,...,...,...,...,...,...,...,...
138111,USD,212.83,8.84,14.28,6.15,224.42,101.77,116.50,51.91,18182.63
138112,USD,2104.32,0.00,147.30,9.18,2260.80,1246.73,1004.89,44.45,10004.74
138113,GBP,1861.85,0.00,372.37,26.94,2261.16,970.95,1263.27,55.87,16442.68
138114,USD,2040.01,174.60,130.58,84.39,2080.38,1042.40,953.59,45.84,8047.00
138115,USD,1878.14,417.27,102.26,9.09,1572.22,884.46,678.67,43.17,4107.38

In [28]:
# display all currency in the dataset
df['currency'].unique()

<StringArray>
['USD', 'EUR', 'INR', 'CAD', 'GBP', 'AUD', 'AED']
Length: 7, dtype: str

In [29]:
# exchange rates as of 2026-10-22
currency_to_usd = {
    'USD':1, 
    'EUR':1.12, 
    'INR':0.011, 
    'CAD':0.71, 
    'GBP':1.34, 
    'AUD':0.70, 
    'AED':0.27
}
def toUSD(df: pd.DataFrame, cols: list):
    """
    take the data frame and change the selected columns into USD using the currency dict
    """
    for col in cols:
        df[f"{col}_USD"] = df[col] * df['currency'].apply(lambda x: currency_to_usd[x])
        df[f"{col}_USD"] = df[f"{col}_USD"].round(2)
    return df

In [30]:
toUSD(df,moneyCols)[['net_sales','currency','net_sales_USD']]

        net_sales currency  net_sales_USD
0          945.40      USD         945.40
1         2018.41      EUR        2260.62
2          468.35      USD         468.35
3          546.52      USD         546.52
4         2785.27      INR          30.64
...           ...      ...            ...
138111     224.42      USD         224.42
138112    2260.80      USD        2260.80
138113    2261.16      GBP        3029.95
138114    2080.38      USD        2080.38
138115    1572.22      USD        1572.22

[138116 rows x 3 columns]

In [31]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    print(df.describe(include='all'))

          order_id                  order_date order_time order_status  \
count       138116                      138116     138116       138116
unique      138116                         NaN      68991            4
top     ORD-301242                         NaN   14:55:55    Completed
freq             1                         NaN         11       113559
mean           NaN  2023-07-21 10:11:31.662081        NaN          NaN
min            NaN         2021-01-01 00:00:00        NaN          NaN
25%            NaN         2022-04-20 00:00:00        NaN          NaN
50%            NaN         2023-08-01 00:00:00        NaN          NaN
75%            NaN         2024-10-29 00:00:00        NaN          NaN
max            NaN         2025-12-31 00:00:00        NaN          NaN
std            NaN                         NaN        NaN          NaN

       sales_channel  customer_id customer_name   customer_age  gender  \
count         138116       138116        138116  138116.000000  138116
unique             4        24911         21564            NaN       3
top       Mobile App  CUST-014687    John Smith            NaN  Female
freq           55318           19            97            NaN   66439
mean             NaN          NaN           NaN      45.862681     NaN
min              NaN          NaN           NaN      18.000000     NaN
25%              NaN          NaN           NaN      32.000000     NaN
50%              NaN          NaN           NaN      46.000000     NaN
75%              NaN          NaN           NaN      60.000000     NaN
max              NaN          NaN           NaN      74.000000     NaN
std              NaN          NaN           NaN      16.467676     NaN

       customer_segment customer_type customer_city customer_state  \
count            138116        138116        138116         138116
unique                4             3         15516             38
top            Consumer         Loyal  Lake Michael   Pennsylvania
freq              75636        129447           166           9148
mean                NaN           NaN           NaN            NaN
min                 NaN           NaN           NaN            NaN
25%                 NaN           NaN           NaN            NaN
50%                 NaN           NaN           NaN            NaN
75%                 NaN           NaN           NaN            NaN
max                 NaN           NaN           NaN            NaN
std                 NaN           NaN           NaN            NaN

       customer_country  region  customer_postal_code payment_method  \
count            138116  138116         138116.000000         138116
unique                7       5                   NaN              7
top                 USA   South                   NaN    Credit Card
freq              82600   43990                   NaN          41460
mean                NaN     NaN          50210.889310            NaN
min                 NaN     NaN            516.000000            NaN
25%                 NaN     NaN          25509.000000            NaN
50%                 NaN     NaN          50183.000000            NaN
75%                 NaN     NaN          74898.000000            NaN
max                 NaN     NaN          99950.000000            NaN
std                 NaN     NaN          28569.767779            NaN

       payment_status currency shipping_method warehouse  delivery_days  \
count          138116   138116          138116    138116  113559.000000
unique              4        7               4        19            NaN
top              Paid      USD        Standard    WH-014            NaN
freq           104250    82600           62006      7447            NaN
mean              NaN      NaN             NaN       NaN       4.557772
min               NaN      NaN             NaN       NaN       0.000000
25%               NaN      NaN             NaN       NaN       2.000000
50%               NaN      NaN             NaN       NaN       4.000000
75%               NaN      NaN             NaN       NaN       7.000000
max               NaN      NaN             NaN       NaN      14.000000
std               NaN      NaN             NaN       NaN       2.810012

        estimated_delivery_days delivery_status return_status  return_reason  \
count             113559.000000          138116          9462           9462
unique                      NaN               4             1              8
top                         NaN         On Time      Returned  Wrong Product
freq                        NaN           86916          9462           1237
mean                   4.298875             NaN           NaN            NaN
min                    0.000000             NaN           NaN            NaN
25%                    2.000000             NaN           NaN            NaN
50%                    4.000000             NaN           NaN            NaN
75%                    6.000000             NaN           NaN            NaN
max                   10.000000             NaN           NaN            NaN
std                    2.594080             NaN           NaN            NaN

        customer_rating review_sentiment        customer_review  \
count     113559.000000           113559                 113559
unique              NaN                3                     25
top                 NaN         Positive  Good value for money.
freq                NaN            78083                  12237
mean           3.677015              NaN                    NaN
min            1.600000              NaN                    NaN
25%            3.400000              NaN                    NaN
50%            3.700000              NaN                    NaN
75%            4.000000              NaN                    NaN
max            5.000000              NaN                    NaN
std            0.483672              NaN                    NaN

       marketing_channel     campaign_name coupon_code  loyalty_points_earned  \
count             138116             54883       27614          138116.000000
unique                10                17          40                    NaN
top       Organic Search  Default_Campaign      SAVE39                    NaN
freq               27742             22989         731                    NaN
mean                 NaN               NaN         NaN             103.991051
min                  NaN               NaN         NaN               0.000000
25%                  NaN               NaN         NaN              17.000000
50%                  NaN               NaN         NaN              70.000000
75%                  NaN               NaN         NaN             151.000000
max                  NaN               NaN         NaN            1621.000000
std                  NaN               NaN         NaN             115.175640

        loyalty_points_redeemed       quantity    gross_sales  \
count             138116.000000  138116.000000  138116.000000
unique                      NaN            NaN            NaN
top                         NaN            NaN            NaN
freq                        NaN            NaN            NaN
mean                  51.934128       5.615244    1375.384176
min                    0.000000       1.000000       6.310000
25%                    3.000000       3.000000     458.920000
50%                   25.000000       5.000000     995.730000
75%                   71.000000       8.000000    1871.200000
max                 1063.000000      24.000000   16051.190000
std                   73.217692       3.371289    1291.009554

        discount_amount     tax_amount  shipping_cost      net_sales  \
count     138116.000000  138116.000000  138116.000000  138116.000000
unique              NaN            NaN            NaN            NaN
top                 NaN            NaN            NaN            NaN
freq                NaN            NaN            NaN            NaN
mean         237.621614     122.462933      22.278080    1282.503575
min            0.000000       0.340000       0.000000       5.800000
25%           26.327500      34.650000       9.820000     448.200000
50%          103.285000      77.010000      19.190000     950.760000
75%          277.125000     156.200000      30.750000    1744.582500
max         6759.020000    2091.520000     149.520000   16218.000000
std          378.779459     140.939368      16.022739    1169.274669

         product_cost         profit  profit_margin_percentage  \
count   138116.000000  138116.000000             138116.000000
unique            NaN            NaN                       NaN
top               NaN            NaN                       NaN
freq              NaN            NaN                       NaN
mean       708.903449     551.322046                 45.065997
min          1.970000   -1281.590000                -59.550000
25%        207.667500     190.757500                 38.880000
50%        478.955000     408.395000                 46.990000
75%        953.762500     752.845000                 53.770000
max       9963.410000    7083.680000                 77.590000
std        730.044970     516.300936                 13.120357

        customer_lifetime_value is_repeat_customer  customer_order_count  \
count             138116.000000             138116         138116.000000
unique                      NaN                  2                   NaN
top                         NaN               True                   NaN
freq                        NaN             137782                   NaN
mean                8971.639047                NaN              6.990559
min                   22.550000                NaN              1.000000
25%                 5713.570000                NaN              5.000000
50%                 8392.525000                NaN              7.000000
75%                11651.030000                NaN              9.000000
max                30268.440000                NaN             20.000000
std                 4430.506588                NaN              2.444166

        gross_sales_USD  discount_amount_USD  tax_amount_USD  \
count     138116.000000        138116.000000   138116.000000
unique              NaN                  NaN             NaN
top                 NaN                  NaN             NaN
freq                NaN                  NaN             NaN
mean        1330.013089           229.475945      122.497726
min            0.070000             0.000000        0.010000
25%          377.397500            17.810000       26.950000
50%          919.130000            92.220000       68.530000
75%         1823.472500           262.590000      147.880000
max        18231.100000          9057.090000     2802.640000
std         1358.311801           386.506428      166.836427

        shipping_cost_USD  net_sales_USD  product_cost_USD     profit_USD  \
count       138116.000000  138116.000000      138116.00000  138116.000000
unique                NaN            NaN               NaN            NaN
top                   NaN            NaN               NaN            NaN
freq                  NaN            NaN               NaN            NaN
mean            21.214398    1244.249275         685.48107     537.553793
min              0.000000       0.120000           0.03000   -1172.130000
25%              8.460000     367.467500         169.86750     154.020000
50%             18.410000     874.370000         441.29000     374.285000
75%             30.380000    1705.775000         924.50500     733.492500
max            114.900000   16875.300000       11339.23000    9492.130000
std             15.820913    1254.141040         762.60339     564.241379

        profit_margin_percentage_USD  customer_lifetime_value_USD
count                  138116.000000                138116.000000
unique                           NaN                          NaN
top                              NaN                          NaN
freq                             NaN                          NaN
mean                       43.788444                  8707.593093
min                       -59.550000                     0.580000
25%                        34.080000                  4958.670000
50%                        45.440000                  8067.980000
75%                        55.690000                 11724.590000
max                       103.780000                 39071.610000
std                        19.362121                  5250.019134

In [84]:
def seasonal_index(df):
    """
    calculation: Seasonal Index = Period sales ÷ Average period sales in that year
    """
    df["year"] = df['order_date'].dt.isocalendar().year
    df["week"] = df["order_date"].dt.isocalendar().week
    # Weekly sales by country and category
    sales = (df.groupby(["year", "week"], as_index=False)
            ["net_sales_USD"].sum())
    sales.rename(columns={'net_sales_USD':'period_sales'},inplace=True)
    sales['avg_period_sales'] = sales.groupby(["week"])["period_sales"].transform('mean')
    sales['season_index'] = sales['period_sales'] / sales['avg_period_sales']
    return sales.loc[sales['season_index'] > 1.2]
seasonal_index(df)

     year  week  period_sales  avg_period_sales  season_index
32   2021    32     800330.14     647297.426000      1.236418
209  2025     1     646362.19     517622.901667      1.248713